version: "3.8"

networks:
  corp:
    driver: bridge

services:
  api-server:
    container_name: api-server
    image: tropaul322/apiv2
    ports:
      - 3001:3001
    env_file:
      - .env
    environment:
      NODE_ENV: "development"
      PORT: 3001
    networks:
      - corp
    restart: on-failure

  react-client:
    container_name: react-client
    image: tropaul322/front
    ports:
      - 4200:80
    environment:
      NODE_ENV: "development"
      PORT: 4200
    networks:
      - corp
    restart: on-failure