FROM tropaul322/nx-base AS builder

ARG NODE_ENV
ARG BUILD_FLAG
WORKDIR /app/builder
COPY . .
RUN npx nx build catsagram ${BUILD_FLAG}

FROM nginx:1.19.2

WORKDIR /usr/share/nginx/html

COPY --from=builder /app/builder/dist/apps/catsagram ./
COPY --from=builder /app/builder/apps/catsagram/nginx.conf /etc/nginx/nginx.conf