name: "Test and Deploy"
on:
  push:
    branches:
      main
jobs:
  deploy:
    environment: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with: 
          cache: 'npm'
      - name: install deps
        run: npm i -g nx

      - name: Build apps
        run: npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      
      - name: Build and Push development Docker image
        run: sh ./docker-build.sh tropaul322/front tropaul322/apiv2

      - name: Run docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEVELOPMENT_HOST }}
          username: ${{ secrets.DEVELOPMENT_USERNAME }}
          key: ${{ secrets.DEVELOPMENT_SSH_KEY }}
          script: |
            docker pull tropaul322/apiv2:latest
            docker pull tropaul322/front:latest
            docker-compose -f app/docker-compose.yml --compatibility up -d --force-recreate --no-deps
            docker system prune -fa --volumes